# Generated by Django 5.2.6 on 2026-01-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_inventorytransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borroweditem',
            name='return_deadline',
            field=models.DateTimeField(blank=True, help_text='Date and time when the item must be returned', null=True),
        ),
    ]
