# Generated by Django 5.2.6 on 2026-01-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_borroweditem_return_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='borroweditem',
            name='return_status',
            field=models.CharField(choices=[('returned', 'Returned Good Condition'), ('lost', 'Lost Item'), ('damaged', 'Damaged Item')], default='returned', max_length=20),
        ),
        migrations.AlterField(
            model_name='borroweditem',
            name='return_deadline',
            field=models.DateField(blank=True, help_text='Date when the item must be returned (3 days from borrowed date)', null=True),
        ),
    ]
