# Generated by Django 5.2.6 on 2026-01-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_borroweditem_return_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borroweditem',
            name='batch_group_id',
            field=models.CharField(blank=True, db_index=True, help_text='Group identifier for items borrowed together in a batch', max_length=100, null=True),
        ),
    ]
