# Generated by Django 5.2.6 on 2026-01-24 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_add_batch_group_id_to_borroweditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='borroweditem',
            name='item_qr_code',
            field=models.ImageField(blank=True, help_text='Unique QR code for this specific borrowed item', null=True, upload_to='borrowed_item_qr/'),
        ),
        migrations.CreateModel(
            name='EquipmentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_code', models.CharField(help_text="Unique identifier for this instance, e.g., 'LAPTOP-001'", max_length=50, unique=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='instance_qr_codes/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='inventory.supply')),
            ],
            options={
                'verbose_name': 'Equipment Instance',
                'verbose_name_plural': 'Equipment Instances',
                'ordering': ['instance_code'],
            },
        ),
        migrations.AddField(
            model_name='borroweditem',
            name='equipment_instance',
            field=models.ForeignKey(blank=True, help_text='Specific equipment instance borrowed (for individual tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_records', to='inventory.equipmentinstance'),
        ),
    ]
