# Generated by Django 5.2.6 on 2026-01-24 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_add_equipment_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='equipment_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='inventory.equipmentinstance'),
        ),
    ]
