# Generated by Django 5.2.6 on 2026-01-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0025_supplyrequest_equipment_instance"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestorborroweranalytics",
            name="damaged_items",
            field=models.PositiveIntegerField(
                default=0, help_text="Total items damaged by this user"
            ),
        ),
        migrations.AddField(
            model_name="requestorborroweranalytics",
            name="lost_items",
            field=models.PositiveIntegerField(
                default=0, help_text="Total items lost by this user"
            ),
        ),
    ]
