# Generated by Django 5.2.6 on 2026-01-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_requestorborroweranalytics_damaged_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplyrequest",
            name="batch_group_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID to group requests submitted together",
                max_length=100,
                null=True,
            ),
        ),
    ]
