# Generated by Django 5.2.6 on 2026-01-27 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_supplyrequest_batch_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="borroweditem",
            name="supply_request",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific request that this item was issued from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issued_items",
                to="inventory.supplyrequest",
            ),
        ),
    ]
