# Generated by Django 5.2.6 on 2026-01-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0028_borroweditem_supply_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplyrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("released", "Released"),
                    ("rejected", "Rejected"),
                    ("returned", "Returned"),
                    ("partially_returned", "Partially Returned"),
                    ("returned_with_issues", "Returned with Issues"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
